"""update cascade relationship name similar to the class name

Revision ID: 086952bf30c9
Revises: 27aeacbe05ab
Create Date: 2026-05-09 23:48:32.263261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '086952bf30c9'
down_revision: Union[str, Sequence[str], None] = '27aeacbe05ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_journal_journal_id'), table_name='daily_journal')
    op.drop_table('daily_journal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_journal',
    sa.Column('journal_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('polarity_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('daily_journal_user_id_fkey')),
    sa.PrimaryKeyConstraint('journal_id', name=op.f('daily_journal_pkey'))
    )
    op.create_index(op.f('ix_daily_journal_journal_id'), 'daily_journal', ['journal_id'], unique=False)
    # ### end Alembic commands ###
