"""add darkmode column in user table

Revision ID: 25f7739d424b
Revises: b95ac00383c0
Create Date: 2026-04-28 22:54:23.861701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25f7739d424b'
down_revision: Union[str, Sequence[str], None] = 'b95ac00383c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Clinic_clinic_id'), table_name='Clinic')
    op.drop_index(op.f('ix_Clinic_name'), table_name='Clinic')
    op.drop_table('Clinic')
    op.drop_index(op.f('ix_recent_activity_id'), table_name='recent_activity')
    op.drop_table('recent_activity')
    op.drop_index(op.f('ix_assessment_result_result_id'), table_name='assessment_result')
    op.drop_table('assessment_result')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.add_column('users', sa.Column('isDarkMode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isDarkMode')
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name=op.f('password_reset_tokens_user_email_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_tokens_pkey'))
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_table('assessment_result',
    sa.Column('result_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('anxiety_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anxiety_severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('depression_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('depression_severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('stress_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stress_severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('assessment_result_user_id_fkey')),
    sa.PrimaryKeyConstraint('result_id', name=op.f('assessment_result_pkey'))
    )
    op.create_index(op.f('ix_assessment_result_result_id'), 'assessment_result', ['result_id'], unique=False)
    op.create_table('recent_activity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('recent_activity_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recent_activity_pkey'))
    )
    op.create_index(op.f('ix_recent_activity_id'), 'recent_activity', ['id'], unique=False)
    op.create_table('Clinic',
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('clinic_id', name=op.f('Clinic_pkey'))
    )
    op.create_index(op.f('ix_Clinic_name'), 'Clinic', ['name'], unique=False)
    op.create_index(op.f('ix_Clinic_clinic_id'), 'Clinic', ['clinic_id'], unique=False)
    # ### end Alembic commands ###
