"""add cascade in user table and timezone true in recent_activity table

Revision ID: 27aeacbe05ab
Revises: af93e7bcc64d
Create Date: 2026-05-09 17:04:36.859746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27aeacbe05ab'
down_revision: Union[str, Sequence[str], None] = 'af93e7bcc64d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_journal_journal_id'), table_name='daily_journal')
    op.drop_table('daily_journal')
    op.alter_column('recent_activity', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recent_activity', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('daily_journal',
    sa.Column('journal_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('polarity_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('daily_journal_user_id_fkey')),
    sa.PrimaryKeyConstraint('journal_id', name=op.f('daily_journal_pkey'))
    )
    op.create_index(op.f('ix_daily_journal_journal_id'), 'daily_journal', ['journal_id'], unique=False)
    # ### end Alembic commands ###
