"""update column names to follow underscore convention

Revision ID: 27eee91ef9f0
Revises: 086952bf30c9
Create Date: 2026-05-12 15:53:53.519366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27eee91ef9f0'
down_revision: Union[str, Sequence[str], None] = '086952bf30c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_journal_journal_id'), table_name='daily_journal')
    op.drop_table('daily_journal')
    op.add_column('users', sa.Column('dark_mode', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_email_notification', sa.Boolean(), nullable=True))
    op.drop_column('users', 'email_notifications')
    op.drop_column('users', 'isDarkMode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isDarkMode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_email_notification')
    op.drop_column('users', 'dark_mode')
    op.create_table('daily_journal',
    sa.Column('journal_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('polarity_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('daily_journal_user_id_fkey')),
    sa.PrimaryKeyConstraint('journal_id', name=op.f('daily_journal_pkey'))
    )
    op.create_index(op.f('ix_daily_journal_journal_id'), 'daily_journal', ['journal_id'], unique=False)
    # ### end Alembic commands ###
