"""add latitute and longitude in user model

Revision ID: 32520add3086
Revises: e8084a0a160a
Create Date: 2026-04-09 23:04:04.265019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32520add3086'
down_revision: Union[str, Sequence[str], None] = 'e8084a0a160a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_result_result_id'), table_name='assessment_result')
    op.drop_table('assessment_result')
    op.drop_index(op.f('ix_Clinic_clinic_id'), table_name='Clinic')
    op.drop_index(op.f('ix_Clinic_name'), table_name='Clinic')
    op.drop_table('Clinic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clinic',
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('clinic_id', name=op.f('Clinic_pkey'))
    )
    op.create_index(op.f('ix_Clinic_name'), 'Clinic', ['name'], unique=False)
    op.create_index(op.f('ix_Clinic_clinic_id'), 'Clinic', ['clinic_id'], unique=False)
    op.create_table('assessment_result',
    sa.Column('result_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('anxiety_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anxiety_severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('depression_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('depression_severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('stress_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stress_severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('assessment_result_user_id_fkey')),
    sa.PrimaryKeyConstraint('result_id', name=op.f('assessment_result_pkey'))
    )
    op.create_index(op.f('ix_assessment_result_result_id'), 'assessment_result', ['result_id'], unique=False)
    # ### end Alembic commands ###
