"""update foreign key to user_id

Revision ID: 6010ed19947d
Revises: ad2fea325dad
Create Date: 2026-05-12 17:14:51.060734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6010ed19947d'
down_revision: Union[str, Sequence[str], None] = 'ad2fea325dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('password_reset_tokens_user_email_fkey'), 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['user_id'])
    op.drop_column('password_reset_tokens', 'user_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('password_reset_tokens_user_email_fkey'), 'password_reset_tokens', 'users', ['user_email'], ['email'])
    op.drop_column('password_reset_tokens', 'user_id')
    # ### end Alembic commands ###
