"""remove back_populates

Revision ID: 73b32f3bb49e
Revises: 843e28663155
Create Date: 2026-05-21 22:11:24.680784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73b32f3bb49e'
down_revision: Union[str, Sequence[str], None] = '843e28663155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_result_result_id'), table_name='assessment_result', if_exists=True)
    op.execute('DROP TABLE IF EXISTS "assessment_result" CASCADE')
    
    op.drop_index(op.f('ix_Message_message_id'), table_name='Message', if_exists=True)
    op.execute('DROP TABLE IF EXISTS "Message" CASCADE')
    
    op.drop_index(op.f('ix_ChatHistory_chat_id'), table_name='ChatHistory', if_exists=True)
    op.execute('DROP TABLE IF EXISTS "ChatHistory" CASCADE')

    op.execute('DROP TABLE IF EXISTS "Clinic" CASCADE')
    op.execute('DROP TABLE IF EXISTS "daily_journals" CASCADE')
    op.execute('DROP TABLE IF EXISTS "daily_journal" CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_journal',
    sa.Column('journal_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('polarity_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('daily_journal_user_id_fkey')),
    sa.PrimaryKeyConstraint('journal_id', name=op.f('daily_journal_pkey'))
    )
    op.create_index(op.f('ix_daily_journal_journal_id'), 'daily_journal', ['journal_id'], unique=False)
    op.create_table('daily_journals',
    sa.Column('journal_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('daily_journals_user_id_fkey')),
    sa.PrimaryKeyConstraint('journal_id', name=op.f('daily_journals_pkey'))
    )
    op.create_index(op.f('ix_daily_journals_journal_id'), 'daily_journals', ['journal_id'], unique=False)
    op.create_table('Clinic',
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('clinic_id', name=op.f('Clinic_pkey'))
    )
    op.create_index(op.f('ix_Clinic_name'), 'Clinic', ['name'], unique=False)
    op.create_index(op.f('ix_Clinic_clinic_id'), 'Clinic', ['clinic_id'], unique=False)
    # Create ChatHistory (Parent) first in downgrade
    op.create_table('ChatHistory',
    sa.Column('chat_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('ChatHistory_user_id_fkey')),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('ChatHistory_pkey'))
    )
    op.create_index(op.f('ix_ChatHistory_chat_id'), 'ChatHistory', ['chat_id'], unique=False)
    # Then create Message (Child)
    op.create_table('Message',
    sa.Column('message_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['ChatHistory.chat_id'], name=op.f('Message_chat_id_fkey')),
    sa.PrimaryKeyConstraint('message_id', name=op.f('Message_pkey'))
    )
    op.create_index(op.f('ix_Message_message_id'), 'Message', ['message_id'], unique=False)
    op.create_table('assessment_result',
    sa.Column('result_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('anxiety_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anxiety_severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('depression_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('depression_severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('stress_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stress_severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('assessment_result_user_id_fkey')),
    sa.PrimaryKeyConstraint('result_id', name=op.f('assessment_result_pkey'))
    )
    op.create_index(op.f('ix_assessment_result_result_id'), 'assessment_result', ['result_id'], unique=False)
    # ### end Alembic commands ###
