"""update table names to maintain consistency and naming convention

Revision ID: 787717d11849
Revises: 27eee91ef9f0
Create Date: 2026-05-12 16:16:34.940660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '787717d11849'
down_revision: Union[str, Sequence[str], None] = '27eee91ef9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('clinic_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('contact_no', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('clinic_id')
    )
    op.create_index(op.f('ix_clinics_clinic_id'), 'clinics', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_clinics_name'), 'clinics', ['name'], unique=False)
    op.create_table('chat_history',
    sa.Column('chat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_chat_history_chat_id'), 'chat_history', ['chat_id'], unique=False)
    op.create_table('recent_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recent_activities_id'), 'recent_activities', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_history.chat_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=False)
    op.drop_index(op.f('ix_recent_activity_id'), table_name='recent_activity')
    op.drop_table('recent_activity')
    op.drop_index(op.f('ix_Message_message_id'), table_name='Message')
    op.drop_table('Message')
    op.drop_index(op.f('ix_ChatHistory_chat_id'), table_name='ChatHistory')
    op.drop_table('ChatHistory')
    op.drop_index(op.f('ix_Clinic_clinic_id'), table_name='Clinic')
    op.drop_index(op.f('ix_Clinic_name'), table_name='Clinic')
    op.drop_table('Clinic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clinic',
    sa.Column('clinic_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('clinic_id', name=op.f('Clinic_pkey'))
    )
    op.create_index(op.f('ix_Clinic_name'), 'Clinic', ['name'], unique=False)
    op.create_index(op.f('ix_Clinic_clinic_id'), 'Clinic', ['clinic_id'], unique=False)
    op.create_table('ChatHistory',
    sa.Column('chat_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('ChatHistory_user_id_fkey')),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('ChatHistory_pkey'))
    )
    op.create_index(op.f('ix_ChatHistory_chat_id'), 'ChatHistory', ['chat_id'], unique=False)
    op.create_table('Message',
    sa.Column('message_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['ChatHistory.chat_id'], name=op.f('Message_chat_id_fkey')),
    sa.PrimaryKeyConstraint('message_id', name=op.f('Message_pkey'))
    )
    op.create_index(op.f('ix_Message_message_id'), 'Message', ['message_id'], unique=False)
    op.create_table('recent_activity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('recent_activity_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recent_activity_pkey'))
    )
    op.create_index(op.f('ix_recent_activity_id'), 'recent_activity', ['id'], unique=False)
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_recent_activities_id'), table_name='recent_activities')
    op.drop_table('recent_activities')
    op.drop_index(op.f('ix_chat_history_chat_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_clinics_name'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_clinic_id'), table_name='clinics')
    op.drop_table('clinics')
    # ### end Alembic commands ###
