"""add cascade

Revision ID: 7b9834200996
Revises: ed971feab0f6
Create Date: 2026-03-15 16:01:53.348661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b9834200996'
down_revision: Union[str, Sequence[str], None] = 'ed971feab0f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_result_result_id'), table_name='assessment_result')
    op.drop_table('assessment_result')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_result',
    sa.Column('result_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('anxiety_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anxiety_severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('depression_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('depression_severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('stress_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stress_severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('assessment_result_user_id_fkey')),
    sa.PrimaryKeyConstraint('result_id', name=op.f('assessment_result_pkey'))
    )
    op.create_index(op.f('ix_assessment_result_result_id'), 'assessment_result', ['result_id'], unique=False)
    # ### end Alembic commands ###
