"""add cascading to user table and remove column from daily_journal table

Revision ID: 843e28663155
Revises: d5581ecc1a36
Create Date: 2026-05-21 20:09:41.116768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '843e28663155'
down_revision: Union[str, Sequence[str], None] = 'd5581ecc1a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_journals_journal_id'), table_name='daily_journals')
    op.drop_table('daily_journals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_journals',
    sa.Column('journal_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('polarity_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('daily_journals_user_id_fkey')),
    sa.PrimaryKeyConstraint('journal_id', name=op.f('daily_journals_pkey'))
    )
    op.create_index(op.f('ix_daily_journals_journal_id'), 'daily_journals', ['journal_id'], unique=False)
    # ### end Alembic commands ###
