"""remove location column from user model

Revision ID: b95ac00383c0
Revises: 721c0089e5d4
Create Date: 2026-04-09 23:20:40.642319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95ac00383c0'
down_revision: Union[str, Sequence[str], None] = '721c0089e5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
