"""update datatype of columns

Revision ID: d5581ecc1a36
Revises: 6010ed19947d
Create Date: 2026-05-12 22:37:32.196190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5581ecc1a36'
down_revision: Union[str, Sequence[str], None] = '6010ed19947d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_journals_journal_id'), table_name='daily_journals')
    op.drop_table('daily_journals')
    op.alter_column('password_reset_tokens', 'token',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.CHAR(length=4),
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'refresh_token',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'refresh_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'token',
               existing_type=sa.CHAR(length=4),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
    op.create_table('daily_journals',
    sa.Column('journal_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('polarity_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('daily_journals_user_id_fkey')),
    sa.PrimaryKeyConstraint('journal_id', name=op.f('daily_journals_pkey'))
    )
    op.create_index(op.f('ix_daily_journals_journal_id'), 'daily_journals', ['journal_id'], unique=False)
    # ### end Alembic commands ###
